# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-21 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(db_index=True, max_length=12)),
                ('contact_name', models.CharField(blank=True, max_length=128, null=True)),
                ('street_name', models.CharField(blank=True, max_length=256, null=True)),
                ('suburb', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('postcode', models.CharField(blank=True, max_length=6, null=True)),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
